### ISSUE TITLE
Database Crashes when BC is Entered Into New Issue Form

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#10]
The database closes and crashes as soon as Submit is clicked for a new BC that is being entered in.  
Attachment has one BC that was entered successfully, and the second one that caused the crash.
- For Annual Benefit, commas were entered into the Annual Benefit field for the second screen shot.

- This impacts management's ability to enter in BC's.  Workaround for now is to utilize the item that was entered into the first screenshot

[Issues-NewBC-DBCrash.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4076968/Issues-NewBC-DBCrash.docx)

**Comment by mikey2695** [comment]
The commas were indeed causing the error, because the decimal field in SQL is not equipped to handle commas. I have changed this. Commas are now handled in the C# backend before executing the query.
Will go in with rest of changes on Monday after testing.

**Comment by mikey2695** [comment]
Changes are now in effect
