### ISSUE TITLE
Updates Required Checkbox allowing issues to be closed when checked

### ISSUE THREAD

**Issue by NickD0w** [CIMDBORG/CIMMigrationProject#101]
There were issues in IB marked for updates but were allowed to be closed.  Users should be getting the pop-up message that they cannot close an item without Manager Review if updates were required. See me for any specific examples needed.

**Comment by mikey2695** [comment]
Brandon was manager level in the database. I went into the backend and corrected the roles for each member of the team. This is not an issue with the code and should now work.

**Comment by Pawel062** [comment]
Hi Mike, Can we please change that? Managers should not be allowed to close an item marked 'update required' either. The count for my talent then could potentially be skewed. We want to force the user to make updates and the manager to accept the updates before we close anything.

**Comment by Pawel062** [comment]
Looks like now also when we make an update to the category of an item like abend/failure to tech request then it is also giving an error. 
<img width="950" alt="Capture" src="https://user-images.githubusercontent.com/59065602/97450989-afd05c00-1909-11eb-8160-a412ca0e4634.PNG">

**Comment by mikey2695** [comment]
Able to re-create the issue. Being worked on.

**Comment by Pawel062** [comment]
Issue has been fixed. You must make update before we close item.
