### ISSUE TITLE
Add Implementation to the Impact Type drop down

### ISSUE THREAD

**Issue by Pawel062** [CIMDBORG/CIMMigrationProject#108]
Add Implementation  to the Impact Type drop down so we can categorize items as being issues from the implementation or items that we are working on that are related to the current implementation.

**Comment by ops1txj** [comment]
I worked with Mike on adding the status of implementation to all forms with Impact Type fields in the Issues Database.  The status of "Implementation" has been added to every occurrence of the "Impact Type" on all forms in test.  Currently waiting on the upload of the enhancement to the production database.

**Comment by Pawel062** [comment]
Good job Tammy! Once it is implemented we can close this out.

**Comment by mikey2695** [comment]
This was looked over and implemented
