### ISSUE TITLE
Add 'AIP' as a Value for System Impacted

### ISSUE THREAD

**Issue by carrubba24** [CIMDBORG/CIMMigrationProject#113]
To address AIP specific issues, User is requesting we add 'AIP' to the System Impacted list, & Assign all items to Dom.

**Comment by Pawel062** [comment]
Discussed this change on 9/30. @carrubba24 and @NickD0w completed coding on 9/30 and we will be implementing into test shortly.

**Comment by carrubba24** [comment]
Change has been implemented & verified.

**Comment by carrubba24** [comment]
Change has been implemented & verified.
