### ISSUE TITLE
Support Hyperlinks for TFS in Weekly Review / Edit View 

### ISSUE THREAD

**Issue by carrubba24** [CIMDBORG/CIMMigrationProject#115]
Just an idea for the Issue View Screens, whether it's built on the BC/TI # Field or a new field created. 

It would be very convenient if Users are able to open their items in TFS through the Database screens in order to close, reassign, or update Issues / Defects/ Features. 

In TFS, there is an 'email work item' option which creates a hyperlink out of the TFS #. 
![image](https://user-images.githubusercontent.com/59064371/141474316-25f7d324-1cc6-4e07-9f1a-41e889554d5c.png)

**Comment by Pawel062** [comment]
Changes have been implemented to production
