### ISSUE TITLE
Wiki Navigation Critique & Improvements

### ISSUE THREAD

**Issue by carrubba24** [CIMDBORG/CIMMigrationProject#16]
I went ahead and added the first step of organizing the pages in the wiki. 

The Billing/EDI Additional Tasks Pages are now available by going to the Tasks page from the home screen.

UAD, InterimDB & IssuesDB are now available by going to the Projects page from home. 

Let me know your thoughts!

**Comment by NickD0w** [comment]
I like it. Good forward thinking.

**Comment by qdd8jtl** [comment]
Love the organization, Dom!  This will be huge for all of us.  Thanks for helping to get us on the right track.
