### ISSUE TITLE
Strategic Task Listed in Aging Items Does Not Come Up On Main Menu Reminder

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#17]
A Strategic Task listed under Aging Items this week does not come up on reminder that pops up on the main menu that a user has Aging Items requiring an update.  

Use Strategic Task with title 'Develop a Role-based Structure for ISPS' as an example.  
Note - I will hold off on running the weekly aging task for now so this can be looked at.

[Issues-AgingItem.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4104903/Issues-AgingItem.docx)

**Comment by NickD0w** [comment]
Not sure if it's related, just noticed a old issue I had in 400's (775585) would display in Weekly Review with Apps, but did not show in Prioritize By System, and also did not come up as an aging warning, but did populate on the aging report.

**Comment by mikey2695** [comment]
Jan-Marie, the warning is supposed to show between 5 and 6 days since last update (before it actually becomes aging). After this, it does not show. Did it show between 5 and 6 days?

**Comment by qdd8jtl** [comment]
It might have.  The problem is by the time the item should have appeared in aging between the 5-6 days, I would never have noticed because it carried over from the weekend.  

I.E. - last status updated 01/13/20.  5-6 days would be January 18-19th.  I was actually off on January 20th so by the time I would have logged back in to the database, it would be past that time frame (but before I would have run the aging scheduled every Thursday).  Perhaps we should update the criteria so that it always displays until aging is actually run by a manager?  

A lot of people were impacted by Aging this past year for the Strategic Tasks alone, so it might be good to update.  Let me know.  I won't be running Aging until Thursday again.

**Comment by mikey2695** [comment]
Working on this now. Hope to have a fix by tomorrow.

**Comment by mikey2695** [comment]
So I have an idea...
Would it be okay to leave the aging warning on even after an item becomes aging?
For instance...
At 5 days, a strategic task will prompt a warning. Even after it has become an aging item, the warning will still display in red at the top of the screen.
Let me know your thoughts...From a coding standpoint, this is the most effective solution, and I think on the business side it makes sense as well, as it doesn't make sense to get rid of the warning after the items becomes an aging item.

**Comment by qdd8jtl** [comment]
That's a great idea!  Will the message disappear once all aging updates have been made by a user?

**Comment by mikey2695** [comment]
Yes it will. 
I will make this change now and publish the change by Thursday so you can run aging.

**Comment by mikey2695** [comment]
Team,

This has solved. @CIM2AXM (Andrew) has tested this and it has worked. I will publish this change now.

**Comment by mikey2695** [comment]
On second thought, I will wait until tomorrow to push changes.
I would like to make sure the aging warning is gone after updates are made.

**Comment by qdd8jtl** [comment]
Mike - I appreciate the quick turnaround for this.  To make sure we follow the same procedures, especially for version control, can you check with one of the approvers before deciding when to implement a change?  Between this issue and  #19, they could have been pushed tomorrow in one shot.  I'm re-opening this one until we can confirm the aging warning above. 

Approvals should be run by myself, @NickD0w , @brcox90 , @tcoma-ups

**Comment by mikey2695** [comment]
Guys,

We can test this out in the test folder. 
The path is  \\mornas2\CIM\Production\CIM Database Project

**Comment by qdd8jtl** [comment]
Guys I'm not getting to this today.  The almost 3 hour call I was on today put me behind with other things.  Can one of the other approvers take a look at this today?  I'm supposed to run actual aging today, but will most likely run it tomorrow at this rate. @NickD0w , @tcoma-ups, @brcox90

**Comment by NickD0w** [comment]
Just verified with Mike, Working properly. 
When issues are approaching aging you will get the warning as before, but now they will not clear until an update is made. Then I verified it will clear.

**Comment by qdd8jtl** [comment]
Re-opening this issue.  I have 2 strategic tasks that are aging 8 days (one is ISPS the other is the database one) and I am not getting the aging items reminder.  If I have time to attach screenshots, I will.

**Comment by mikey2695** [comment]
This still an issue? Will work on it today if so.

**Comment by qdd8jtl** [comment]
Yes.  I did not get to run Aging yesterday and purposefully left out a status on the 2 strategic tasks under my name.  I don't have a message for Aging when I log on.  If you need me to NOT run aging for now, we can waive this week.

**Comment by mikey2695** [comment]
Gonna work on this ASAP as I have the time today.

**Comment by qdd8jtl** [comment]
All - I'm about to running aging today and I purposefully left my strategic tasks without a status...I do not see the reminder on the main menu.
