### ISSUE TITLE
Add Sort to Manager Weekly Review

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#18]
For Manager/Supervisor Weekly Review, add the following sort below to allow those with multiple systems for easier review during the meeting:

- Sort by System

- Then Sort by User

**Comment by mikey2695** [comment]
We need to talk about this further, I'm slightly confused as to what exactly is needed here.
Do you want the Sort by User to come up after sorting by system?
So hypothetically speaking, after you choose EDI, you want Figueroa, Morgan, Jensen, etc. to pop up as choices in a separate combobox?

**Comment by qdd8jtl** [comment]
Not sorting within the grid view for Weekly Review, but to add sorting for records on the Weekly Review form once I hit Edit/View to go through each of the items for the week.  I am finding that even when I sort by even System on the grid view, when I click on Edit/View, it takes me to where that record lies 
i.e. if an item for CRIS for Dow is 5th on the list -
- Sort on the grid view and that item is at the top of the list
- Click on Edit/View
- The form displays that item for CRIS for Dow, but it is record 5

Can't really show you since there are only 2 items for CRIS for weekly review since yesterday.  Once there are additional items I'll add screenshots if it still doesn't make sense.

**Comment by mikey2695** [comment]
I have made this fix. I will make this ready to test along with Brandon's menu update.

**Comment by mikey2695** [comment]
My change on Issue #18 has been made on LAN, ready for test

**Comment by brcox90** [comment]
Looks good Mike. Got one approval from me.

**Comment by NickD0w** [comment]
I concur... Good to Go.

**Comment by mikey2695** [comment]
Awesome.
@qdd8jtl, please let me know when we are good to go in regards to going live with changes.

**Comment by qdd8jtl** [comment]
Guys - THANK YOU for staying on top of this and getting this going.  I spoke to @NickD0w and have given him the go ahead to sign off on going live with changes.  I trust you guys will follow this same process with other updates moving forward.  For approvals, I think we agreed backup people would be @NickD0w , @brcox90 , @tcoma-ups in the event one of the backups or myself cannot do the verification.  I will leave it up to you guys to decide when to push the changes in whether it be sometime this morning or tomorrow...whatever works.  

Within the next 2 months I will be MIA due to ISPS, but will make it a point to join our weekly meetings and follow the comments in GitHub.  AND if for whatever reason you absolutely need me, send me an IM or call my cell phone.
