### ISSUE TITLE
Issues DB - Add New Record - Planned Comp Date error

### ISSUE THREAD

**Issue by NickD0w** [CIMDBORG/CIMMigrationProject#19]
When adding a new record and filling out the Planned Comp Date, receiving submission error:
![image](https://user-images.githubusercontent.com/59174086/73212003-538ea080-411b-11ea-9eee-ec60c2b55dc3.png)

![image](https://user-images.githubusercontent.com/59174086/73212035-63a68000-411b-11ea-83a2-7f1c2c440611.png)

Re-entering the New Record and leaving the Planned Comp date as default, Record submits with no issues:

![image](https://user-images.githubusercontent.com/59174086/73212183-aff1c000-411b-11ea-9390-ae94749e7700.png)

**Comment by qdd8jtl** [comment]
Work-around for the time being would be to utilize the 'Scheduled Implementation' status note update with the date in the note?

**Comment by NickD0w** [comment]
That would work, or also for now I've discovered you can leave the default and update it once it's submitted.

 With that, I wouldn't consider the issue critical, just an added step to go back and update once the issue is created.

**Comment by mikey2695** [comment]
Team,
This problem has been fixed. This was a result of a single missing quotation mark in SQL (shocker!). 
I have decided to push this update now, as this is a problem that can prevent the team from submitting an issue into the database. No other changes have been made.

**Comment by NickD0w** [comment]
I can confirm the fix Mike implemented has resolved the issue. Planned Comp Date can now be filled out on the initial issue submission.

**Comment by brcox90** [comment]
@mikey2695 think you pointed out how you fixed it in the comments

**Comment by mikey2695** [comment]
Fixed. Code was overwritten I believe (probably my mistake).

**Comment by brcox90** [comment]
Fixed in last update
