### ISSUE TITLE
User updates requested by Manager - no button to clear it once update is made?

### ISSUE THREAD

**Issue by ellenculp** [CIMDBORG/CIMMigrationProject#21]
BC 200010.  Updates made on 1/23 - message still appears on Main Menu page.

**Comment by mikey2695** [comment]
Looking into this Ellen, thank you.

**Comment by mikey2695** [comment]
This fix has been made and will be implemented after testing. The fix has come in the form of a refresh button on the Issues Database menu. This will clear all aging and manager update warnings after the updates have been made.
Pawel, I know you have the same problem presently and I would like you to test this out before I push the change. I will let you know where the test version can be accessed.

**Comment by mikey2695** [comment]
@NickD0w has verified this for me.

**Comment by NickD0w** [comment]
True Story.... Verified, works great.
