### ISSUE TITLE
EDI Database - Add Product Form Design

### ISSUE THREAD

**Issue by mikey2695** [CIMDBORG/CIMMigrationProject#22]
This will be where the new Add Product Form mockup is added.

**Comment by milleniumchilld** [comment]
Team,

Here is the Add Product Form

[Add Product Form.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4124567/Add.Product.Form.docx)

**Comment by jgesualdo** [comment]
Looks Good. Couple of things .
1.  Can we ensure that the email addresses are linked to both the Contact Database and Reports. This way, we will not need to enter the customers email address twice, once in the add product screen and once in the contact database. We will need to link customers email addresses within our products to the contact database for our distribution lists for ER, and Reports for Mark J. 
2. I am not seeing "EDI ID" field. We either need that or "Submit PWR" field. The EDI ID should be visible within either this screen or the PWR screen, I am not sure which but we can discuss.

**Comment by mikey2695** [comment]
1. Emails will be in reports, that is a must do agree. Customer emails only need to be added once in the Add Company screen, so there is no worry there. 
2. This form is for dispatchers to Add a Product to an existing company. For example JG, if you get a request to add 240/5010 tracking to a company that already has 210 billing, you would do it through this form. This explains the lack of an EDI ID or Submit PWR field - these fields are in the search company screen/Open Items Screen
3. Editing a company is a must, I do agree. This can be easily built in as well.

**Comment by milleniumchilld** [comment]
Based on the comments I will make the necessary updates. Thank you

**Comment by brcox90** [comment]
@milleniumchilld  @mikey2695  any update on the design of this form?

**Comment by mikey2695** [comment]
You can close this
