### ISSUE TITLE
EDI Database Design Documents

### ISSUE THREAD

**Issue by milleniumchilld** [CIMDBORG/CIMMigrationProject#23]
(https://github.com/CIMDBORG/CIMMigrationProject/files/4124537/EDI.Database.test.docx)

Team,

Please see attached EDI Database Mockups for your review and comments.

@CIMDBORG/edi

**Comment by brcox90** [comment]
All, 

This issues been open a while with no comments/feedback on it. I've switched the assigned users to members of the EDI team so we can get some feedback on this issue and hopefully get it closed.

@mikey2695  @milleniumchilld

**Comment by mikey2695** [comment]
[EDI DB Design Document.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4518225/EDI.DB.Design.Document.docx)

**Comment by milleniumchilld** [comment]
[EDI DB Interface Design Document.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4518676/EDI.DB.Interface.Design.Document.docx)

**Comment by milleniumchilld** [comment]
Database Design Updates 
[EDI DB Interface Design Document.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4549049/EDI.DB.Interface.Design.Document.docx)

**Comment by milleniumchilld** [comment]
Database Design Updates (Q&A test session 1) 
[EDI DB Interface Design Document.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4664336/EDI.DB.Interface.Design.Document.docx)

**Comment by milleniumchilld** [comment]
Database Design Updates (test session 2 & 3)
[EDI DB Interface Design Document.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4847101/EDI.DB.Interface.Design.Document.docx)

**Comment by milleniumchilld** [comment]
Database Design Updates (test session 4)
[EDI DB Interface Design Document.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/5097585/EDI.DB.Interface.Design.Document.docx)

**Comment by milleniumchilld** [comment]
Database Design Updates (test session 5)
[EDI DB Interface Design Document.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/5241765/EDI.DB.Interface.Design.Document.docx)
