### ISSUE TITLE
Improve Accuracy for My Talent EOY Queries 

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#24]
The My Talent End of Year queries need to be re-worked so that they are more accurate when it comes to reporting for end of year.  @mikey2695 - could you please provide @NickD0w the queries  and tables that are used to produce the information below?  I would like him to start taking a look at what's going on with them so I can work with him on making sure they are accurate for this year.

- % effectiveness based on total number of Items Not Needing Updates divided by Total Items Entered for current year
NOTE - Total number of items not needing updates calculated based by subtracting total items flagged by manager needing updates from Total items opened for current year.

- % effectiveness for Aging based on the total number of unique weeks divided by Total number of weeks in the year (52)
NOTE - total number of weeks in the year should be calculated based on the total actual number of weeks aging is run by a manager.

**Comment by mikey2695** [comment]
@NickD0w and @mortii09, here is the query for effectiveness...I see a few flaws myself, we can discuss later in our meeting if you guys would like:

SELECT New_Issues.Assigned_To, [Updates Done] AS[Items Not Needing An Update], COUNT(ID) AS[Total Open Items],  
CAST([Updates Done] as decimal(12,1))/ CAST(COUNT(ID) as decimal(12,1)) * 100 AS[% Effectiveness]  
FROM New_Issues INNER JOIN(SELECT COUNT(ID) AS [Updates Done], Assigned_To FROM New_Issues WHERE Manager_Update_Bit = 0 AND Opened_Date > '1/1/2019' 
GROUP BY Assigned_To) n1  
ON New_Issues.Assigned_To = n1.Assigned_To WHERE Opened_Date > '1/1/2019' GROUP BY New_Issues.Assigned_To, [Updates Done];

**Comment by mikey2695** [comment]
Messing around myself, I got this and it seems fine:

SELECT New_Issues.Assigned_To, [Updates Done] AS[Items Not Needing An Update], COUNT(ID) AS[Total Open Items],  
CAST([Updates Done] as decimal(12,1))/ CAST(COUNT(ID) as decimal(12,1)) * 100 AS[% Effectiveness]  
FROM New_Issues INNER JOIN(SELECT COUNT(ID) AS [Updates Done], Assigned_To FROM New_Issues WHERE (LEN(Mgr_Notes) = 0 OR Mgr_Notes IS NULL)
AND Opened_Date > '1/1/2020' 
GROUP BY Assigned_To) n1  
ON New_Issues.Assigned_To = n1.Assigned_To WHERE Opened_Date > '1/1/2020' GROUP BY New_Issues.Assigned_To, [Updates Done];

Logic behind this: @Pawel062, I just realized we never really needed a manager_update_bit field in the New_Issues table - reason being that if a manager is requesting an update, the Mgr_Notes field will have something in it regardless. We can discuss further later on. I think this query is dead on accurate, though. 
We live and we learn yall.

**Comment by mikey2695** [comment]
Brain is going today so thoughts on the second query (% effectiveness for Aging based on the total number of unique weeks divided by Total number of times aging is run throughout the year)
We need to obviously track the number of times aging has been run throughout the year - maybe this would be good as an additional column to the History table? Thoughts? That field would probably have to be manipulated via C#

**Comment by mortii09** [comment]
@mikey2695 hey yo, is the query mentioned above the finished product? ill review it.

**Comment by mikey2695** [comment]
@mortii09 yessir

**Comment by mortii09** [comment]
@qdd8jtl the first requirement is fullfilled by the above query. I have peer reviewed the query .. the logic and everything checks out - its accurate. 

@mikey2695 we do not have a query for the second requirement correct? or @Pawel062  do we have a query for the second requirement Jan-Marie has requested?

**Comment by mikey2695** [comment]
We do not have the query done for the second query, correct

**Comment by Pawel062** [comment]
I have to check through my notes but I don't have one on a quick glance.
