### ISSUE TITLE
Test Database Upload/Revision w. New Changes

### ISSUE THREAD

**Issue by brcox90** [CIMDBORG/CIMMigrationProject#25]
Wanted to open an issue to discuss this because while we need pages that have been updated/fixed to be uploaded in the test database so everything is current, we also need to discuss the process of uploading this test database. 

The reason I bring this up is because, as the team know, I've been working on coding in the new menu for the database, and have been testing it to see if it's working up to our expectation. We're now on the second time it's been overwritten back to the old menu, despite that page not receiving any update. Every time that happens we lose hours of work. 

A new method for keeping the test database should be discussed among the team, because the current way will cause a massive amount of double work as more people work on different databases and different enhancements. .

**Comment by NickD0w** [comment]
Definitely a good issue to bring up, specially as more people will begin wanting to code. Following the GitHub process follow of Push/Pull/Merge requests and creating personal branches will keep this from happening.

Hi level process flow is like this:

Brandon makes a Pull Request, downloading an exact replica of everything locally to his machine.
Doing so creates a separate branch, the "Brandon-Branch". It's separate and safe from being overwritten, he can play, test, do whatever. Then when ready to present and get feedback, he'll make a Push Request, at this time we can all view his changes, make comments, etc.... Once we agree it's good to go, the Push Request becomes a Commit and Merge, essentially becoming the new Main Brach in production. 

Doing this eliminates the need for a separate Test DB, as each Pull Request is essentially a personal Test DB. However, if we want an additional level of protection we can treat the Test DB like the Main production branch, following the same process so we aren't overwriting, etc. and once we're happy with the test DB, merge that into the main line.

**Comment by qdd8jtl** [comment]
Great points, guys.  I know we discussed approvals and utilizing the Push/Pull Requests, but want to discuss this at our meeting tomorrow to make sure we start following this.  No matter how small the change, we need to make sure we follow a process here as we start moving forward.  We will also discuss priorities as a few late breaking items have come up within the past week.

**Comment by mikey2695** [comment]
Agreed all around in regards to the test database. This is something that needs to be discussed tomorrow at the meeting like Jan-Marie has said.

**Comment by brcox90** [comment]
Addressed by @mikey2695 @mortii09 @tcoma-ups and @NickD0w
