### ISSUE TITLE
New Menu Demo

### ISSUE THREAD

**Issue by brcox90** [CIMDBORG/CIMMigrationProject#26]
This issue is to get sign-off on the new menu so that it can be placed into production.

[ScreenCap.zip](https://github.com/CIMDBORG/CIMMigrationProject/files/4139684/ScreenCap.zip)

**Comment by NickD0w** [comment]
Walked through the new menu with Brandon & Jan-Marie. Looks & Works great. 
Approved to implement into production.

**Comment by brcox90** [comment]
@mikey2695 @Pawel062 The work for this is completed in the test database, as well as combining pages and windows in c# where necessary. This is a pretty large code change, and should be discussed with myself (since I know exactly what's changing) and Jan-Marie and Nick (for final go ahead) before being implemented. We should do this ASAP.

**Comment by mikey2695** [comment]
Agreed Brandon. I have held off on implementing the menu because of that reason. This must be discussed tomorrow early on.

**Comment by brcox90** [comment]
[Coding Changes.txt](https://github.com/CIMDBORG/CIMMigrationProject/files/4154342/Coding.Changes.txt)

Attached is a list of classes that were changed. This list can be used to integrate the code located on the test DB in order to get changes into the live DB. Please let me know if there are any questions regarding changes. Looking to get this done as smoothly as possible.

**Comment by mikey2695** [comment]
Database is ready to test on LAN. Should be good to go. Please let me know if any issues arise.

**Comment by Pawel062** [comment]
should we report issues here or make a new item for them? I already found some bugs.

**Comment by NickD0w** [comment]
I would say add them here, since this is not implemented yet. Keep the Issues for production items.

**Comment by mikey2695** [comment]
Add them here for sure. Easier to keep track of here too.

**Comment by Pawel062** [comment]
Issues I am seeing:
1. when you click on DB list without the left side bar expanded, it will crash. If you click any other they work still. 
2. when you click through the menu and open new windows, the old window does not close so for example I logged in, clicked home button and there are 2 home windows. If I click add record I will now have a 3rd window open and the main menu moves to top of the screen. If i click Home again, i have 4 windows now. 
3. when I go to weekly review with apps and go into CDC, the update/add status buttons have some of the text cut off ; the arrows are now purple boxes (along with the update/add status) ; and also the heading row of the status box has all tiny text
4. In the All Open Items window, the edit/view is cut off and once again the heading rows have tiny text.
5. When you open a drop down, it will overlap and show the text of the box above it. 
Screenshots: 
<img width="881" alt="2 0 0 4_Issue4" src="https://user-images.githubusercontent.com/59065602/73767153-10e54d80-4745-11ea-8b4d-e07d3143c2b4.PNG">
<img width="197" alt="2 0 0 4_Issue5" src="https://user-images.githubusercontent.com/59065602/73767154-10e54d80-4745-11ea-84c2-e6f4826631cd.PNG">
<img width="957" alt="2 0 0 4_Issue2" src="https://user-images.githubusercontent.com/59065602/73767155-117de400-4745-11ea-8f50-778135794f65.PNG">
<img width="887" alt="2 0 0 4_Issue3" src="https://user-images.githubusercontent.com/59065602/73767156-117de400-4745-11ea-9671-bd1ec6494a93.PNG">

**Comment by brcox90** [comment]
Is anybody in the LAN copy Mike mentioned at the moment?

**Comment by NickD0w** [comment]
I am not.

**Comment by mikey2695** [comment]
All clear here.

**Comment by Pawel062** [comment]
i am also out

**Comment by brcox90** [comment]
From what Pawel pointed out, only the first two issues are resulting from the menu implementation (the multiple windows without a close, and the crash when a button was clicked). 

Of those issues #'s 1, 2, and 4 have been fixed. 

The purple buttons seem to be something the debugger in Visual Studio does on its own (similar to adding the purple underline on the login page). That'll go away when live. 

The combobox wasn't showing funny in production, and wasn't changed by the code for the menu at all, so it shouldn't show wrong outside of the debugger in Visual Studio. Unfortunately, that's something we're going to have to address if it's still wonky after the update is pushed since the code looks fine for it and hasn't been touched.

**Comment by mikey2695** [comment]
Gotcha
Let me know when this is verified. I have one other fix (#19) to implement with this one as well and we will push it all in one go

**Comment by brcox90** [comment]
@Pawel062 went through and tested the changes. Last I heard he said everything was good to go.

**Comment by Pawel062** [comment]
I give my stamp of approval.

**Comment by mikey2695** [comment]
Sounds good. Will make changes to LAN copy (my change is only a change to a query)
