### ISSUE TITLE
Enhance the BC Approval Process for Managers and TT

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#27]
This issue is a request from TT to allow a status that is updated for BC's that are in review to be automatically saved.

Current Process - Managers review and put the BC's in BC Submitted after review.  TT goes in to those same BC's shortly after, reviews them, then updates the status to BC Approved.
- For each of these, the Update button must be clicked in order to save the status and then move on to the next record

Enhancement - When either a Manager or Controller updates the status for a BC, automatically save the status update which will allow management to scroll to the next record without having to click on 'Update'.  

* Note - this request is only for BC's and to have the statuses automatically save.  However, we can discuss other options if you guys can comment below.  **The ask is to have this enhancement in sooner than later so that it saves time at the management level**

**Comment by mortii09** [comment]
I think this is a must, and should be implemented for all levels of user access. I personally hate the update button very user-unfriendly.

**Comment by mortii09** [comment]
Hello all, just wanted to update, i have tested this case, so for users like me ( specilists ) the update functionality is not required. i had just been paranoid and always had been clicking update just to be safe after being scarred.

**Comment by qdd8jtl** [comment]
@brcox90 will start working on this.  Thanks, Brandon!

**Comment by brcox90** [comment]
This change was made and implemented for both user and managers. Fully functional in test.

**Comment by mikey2695** [comment]
Awesome, @NickD0w @tcoma-ups @qdd8jtl please let me know when we have the okay to push changes (I know this was a high priority issue)

**Comment by brcox90** [comment]
Personally in favor of an 8am push

**Comment by brcox90** [comment]
Actually found a bug so this is still incomplete

**Comment by mikey2695** [comment]
No worries Brandon.
