### ISSUE TITLE
Form style effected by changes to App.xaml file

### ISSUE THREAD

**Issue by mikey2695** [CIMDBORG/CIMMigrationProject#28]
I noticed that there has been an issue with the changes to App.xaml - the purple arrows, and blank combobox backgrounds below:

![image](https://user-images.githubusercontent.com/52287707/73849914-c45b4a00-47f8-11ea-9686-315841c53351.png)

I have found that this is caused by these lines added to the App.xaml code:

ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
            </ResourceDictionary.MergedDictionaries>

Please let me know ASAP it this is just an aesthetic issue, or if this is an issue that would prevent us from pushing the new changes @NickD0w @tcoma-ups @brcox90

**Comment by brcox90** [comment]
I think these can be fixed by adding a Static Resource to the style of these items. Will get that done now

**Comment by mikey2695** [comment]
Sounds good Brandon

**Comment by NickD0w** [comment]
Nice, geting that fixed before going live, would of course be ideal. You know that's one of the first things people will see and flag as an issue.

**Comment by brcox90** [comment]
The style of the buttons and comboboxes have been fixed.

**Comment by mikey2695** [comment]
Awesome. @NickD0w please verify and tell me whether we're good to go live

**Comment by mortii09** [comment]
good stuff

**Comment by NickD0w** [comment]
Verified, Good to Go!
