### ISSUE TITLE
ISSUES DB - Table Edit/View Button adjustment

### ISSUE THREAD

**Issue by NickD0w** [CIMDBORG/CIMMigrationProject#29]
Couple minor cosmetic items:

In Table View of issues, the Edit/View button is slightly cut off...
![image](https://user-images.githubusercontent.com/59174086/73864736-26737980-4810-11ea-8177-b9c9e0bc0012.png)

Also noticed in the Search Items table, the Opened Date needs adjustment...
![image](https://user-images.githubusercontent.com/59174086/73864894-633f7080-4810-11ea-9053-b7265b49e04b.png)

**Comment by brcox90** [comment]
Fixed these as well. Keep pointing them out. By Monday all should be perfect format wise

**Comment by brcox90** [comment]
Fixed in last update
