### ISSUE TITLE
Issues DB - Weekly Review w/Apps - Add 'Requested By' Information

### ISSUE THREAD

**Issue by kaylori77** [CIMDBORG/CIMMigrationProject#30]
Suggesting an enhancement to the Issues DB-->Weekly Review w/Apps form.
Add a 'Requested By' field to store the information of who (if applicable) requested the issue that was documented in the DB.
Seems that this question is asked frequently during these meetings & it may be useful to have.

Attaching screen shot below...

![image](https://user-images.githubusercontent.com/60524314/77782149-34ce5c80-702d-11ea-95b9-7a249d3ba5fb.png)

**Comment by mikey2695** [comment]
Makes sense to me, we can definitely find space to add the requested by field

**Comment by qdd8jtl** [comment]
Can we also utilize this same issue to add **Priority Number** on the Weekly Review form rather than opening another separate issue?

**Comment by Pawel062** [comment]
combined into 1 issue
