### ISSUE TITLE
All codes files now in github

### ISSUE THREAD

**Issue by mikey2695** [CIMDBORG/CIMMigrationProject#32]
You can now access all the code files on here. You can pull/create a new branch and mess around with code there.

**Comment by NickD0w** [comment]
Nice!! Thanks Mike, 
@mortii09 @brcox90 @qdd8jtl @carrubba24 @Pawel062 @tcoma-ups 
so we should no longer need to use a separate Test DB from the Lan for future coding. 
Just the Mainline, and the individual branches we create when we pull from Git.
