### ISSUE TITLE
CDC Error File Database 

### ISSUE THREAD

**Issue by tcoma-ups** [CIMDBORG/CIMMigrationProject#34]
Opening this issue for the work being done on the CDC Error File Database. Brandon has completed most of the design and queries have been built, however currently we are running into the issue of importing the files from the mainframe to the database with specific data from the files. Morty is currently working on the transition of a SQL query to perform the same task in the C# front end and ultimately would implement a SSIS package to automatic the download and import. 

That's a overall idea on what's currently going on, Brandon and Morty may be able to speak to this more.

If anyone has anything they may be able to add to help, please feel free.

**Comment by brcox90** [comment]
I created an SSIS package for this. Now, just need to figure out how to execute the package using the front end. Idk if you know how to do that Morty.

Everything I'm seeing online is telling me to use methods that return errors and do nothing.

**Comment by NickD0w** [comment]
I'm definitely not an SSIS expert, but can you trigger the SSIS package using a query statement?
If so, my thought would be to use the code I sent you earlier Brandon, to create a C# / SQL-S connection then send the Query command through C#. - Just brain storming.

**Comment by Pawel062** [comment]
we need morty in here but from my limited memory of when Johnny and I did this with Andy, you create the ssis package, send it to him, he loads it to his server, and then sets up the server to run it at a certain time/day(s)

**Comment by brcox90** [comment]
@NickD0w I've got no idea if that's possible. I've seen a lot of methods online and none of them are current.

@Pawel062  this SSIS package was made for a different reason. Eventually we'll do that but if we can't trigger this package from the front end it defeats the purpose of migrating this DB. The CDC user would end up doing more work than they're doing now for the same result.

**Comment by brcox90** [comment]
Solved it! Will get code posted to Github after Monday's implementation
