### ISSUE TITLE
Application Priority List Export with 300's Items Generates Error

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#35]
When clicking on Reports - Application Priority Report - Include 300's items, the message in the attached screenshot appears and the priority list cannot be exported to Excel.

[Issues-PL-Export300s.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4181423/Issues-PL-Export300s.docx)

**Comment by qdd8jtl** [comment]
Did something change recently with the Exporting of priority lists?  @brcox90 also noticed we have missing BID numbers when going into Browse Item - Browse Open Items and exporting Priority List to Excel for this week.

[Issues-BrowseOpenItems.xlsx](https://github.com/CIMDBORG/CIMMigrationProject/files/4181521/Issues-BrowseOpenItems.xlsx)

**Comment by mikey2695** [comment]
Haven't touched that in about 2-3 months
