### ISSUE TITLE
Cassie's Report Formatting request from Pune 

### ISSUE THREAD

**Issue by tcoma-ups** [CIMDBORG/CIMMigrationProject#38]
Opening this issue to document the below format requested by Pune for the report this database produces. Other than the columns, they are requesting that we have the new records highlighted, this is how the original Access Database produced this form.

![image](https://user-images.githubusercontent.com/59063096/74244162-02e87d00-4caf-11ea-9f20-a19650189f8d.png)

**Comment by milleniumchilld** [comment]
@tcoma-ups is this something you need for me to design?

**Comment by tcoma-ups** [comment]
thanks @milleniumchilld, but I think that screenshot will do... its just an excel export. 

@brcox90 would a mock up help you out with this?

**Comment by brcox90** [comment]
@tcoma-ups @milleniumchilld  I think a screenshot works fine for this.

**Comment by milleniumchilld** [comment]
Thank you
