### ISSUE TITLE
Establish a Detailed Procedure for Data Backups

### ISSUE THREAD

**Issue by carrubba24** [CIMDBORG/CIMMigrationProject#48]
In order to move forward in migration / implementing new features to the application, our most important task is to establish a clear process in backing up the SQL Database for the application. 

The backup process must be detailed and meticulous, and must be approved by the team.

**Comment by NickD0w** [comment]
@mortii09  will take on creating a backup.
@carrubba24  will work with Morty to document the procedure for the Wiki

**Comment by mikey2695** [comment]
Me and @mortii09 have figured out how to backup AND restore the database from said backup. Next step is to work with @carrubba24 to document the procedure in the wiki (it's basically a 3-4 click procedure that takes a few seconds).

**Comment by mortii09** [comment]
Me and dom had a meeting yestarday in regards to the documenating the backup and restore process.

**Comment by mikey2695** [comment]
oh

**Comment by carrubba24** [comment]
Will be making a detailed " SQL Backup / Restore " wiki page in the following days

**Comment by tcoma-ups** [comment]
Closing this issue due to wiki completed by Dom
