### ISSUE TITLE
Wiki: Billing Additional Tasks

### ISSUE THREAD

**Issue by carrubba24** [CIMDBORG/CIMMigrationProject#50]
So as it turns out, I am currently the only one with control to enter items in the Billing Additional Task Wiki Page. 
So until we can find a better solution and to get that page up to date quickly,  continue to log your tasks in the OneNote. I will check the OneNote frequently & make sure it stays up to date. 
In the mean time I will look for alternate solutions and we can discuss the best one when we meet next Friday.

**Comment by NickD0w** [comment]
One possible solution Dom is looking more into is adding an Excel Doc to the Code pages we can update from there.... Thoughts??

**Comment by brcox90** [comment]
He ran this idea by me as well. It has my vote. Would improve the current process a great deal.

**Comment by mikey2695** [comment]
Sure, makes tons of sense.

**Comment by carrubba24** [comment]
Sweet, I will make a 'prototype' excel sheet that we can test out and approve.

If anyone has any doubts or suggestions just let me know.

**Comment by tcoma-ups** [comment]
Closing this issue due to it being located in the code tab under "BillingAdditionalTasks.xlsx"
