### ISSUE TITLE
EDI/Billing Navigation Menu 

### ISSUE THREAD

**Issue by milleniumchilld** [CIMDBORG/CIMMigrationProject#6]
[new mockups.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4057346/new.mockups.docx)

**Comment by milleniumchilld** [comment]
The attached word document is the revised mock ups for the EDI/Billing dashboard. The user will be greeted with the welcome screen and the UPS symbol will be displayed as a placeholder until a dashboard menu option is selected. Dashboard menu is also collapsible.

Page 1: Welcome Screen 

Page 2: EDI option has been selected and all relevant databases are displayed

Page 3: Billing option has been selected and all relevant databases are displayed.

**Comment by milleniumchilld** [comment]
Please feel free to give your thoughts...

**Comment by qdd8jtl** [comment]
I love the idea of the dashboard on the side!  Especially since there will be more databases added eventually.  Instead of the buttons appearing, what do you guys think of having expandable and collapsible items.  i.e. - click on Billing and it expands a listing of Billing systems, then click on the Billing system, and it expands to list all the relevant databases for that system.  Same thing for EDI.  And maybe also utilize the dashboard to have the ability to pin a user's favorites.

P.S. - I'm leaving the design to Sophia.  It took me forever just to get the tiny little bit of a screenshot I just uploaded.

**Comment by milleniumchilld** [comment]
That is also an option, I will do another mock up with the expandable and collapsible items and see what everyone thinks.  Thank you

**Comment by NickD0w** [comment]
I agree, that's the best, cleanest approach. I would envision something like the UPS intranet site guide...

![image](https://user-images.githubusercontent.com/59174086/72348521-9a56b200-36a8-11ea-890c-0f15dc760270.png)


But with the drop down ability to hide and pin Jan-Marie said, that would be perfect. 
No need for big buttons, hyperlinks will be cleaner in the long run.

**Comment by Pawel062** [comment]
Only thing with hyperlinks is ability to use your finger to click on them. We either have to make the text big or add spacing. We can brainstorm ideas though and also see how touch friendly the team wants the menu to be.

**Comment by NickD0w** [comment]
Another factor to consider is coding complexity to build and maintain.

Mike - thoughts on what is easier from a coding stances, initially and future maintenance?

**Comment by milleniumchilld** [comment]
[new mockups.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4059692/new.mockups.docx)

I revised the mockups with the feedback given by everyone, thank you. I also added a reports section, not sure if it is needed, let me know what you think.

**Comment by mikey2695** [comment]
It's all personal preference, from a coding perspective there is no difference in terms of complexity. I like it though, and it's a good way to keep the menu nice and neat as we continue to add databases.

**Comment by mikey2695** [comment]
Hey Brandon, 

Pawel mentioned to me that you were trying to do a hamburger menu for the menu screen. I believe something like this may be what you were looking for:

<img width="205" alt="Capture" src="https://user-images.githubusercontent.com/52287707/72461235-8e4c1c80-379c-11ea-8ea2-dc7b48435f41.PNG">

Here's the code. The Expander control is very useful when it comes to menus. 

<img width="644" alt="Capture" src="https://user-images.githubusercontent.com/52287707/72461271-a15eec80-379c-11ea-95f8-b8144c9b7366.PNG">

**Comment by mikey2695** [comment]
Also dropping this down here for everyone...Here is the documentation for the System.Windows.Controls Namespace (so think of this as documentation for XAML design, which has classes, properties, methods, etc.) 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls?view=netframework-4.8#classes

**Comment by brcox90** [comment]
Implemented a few updates ago
