### ISSUE TITLE
Left and Right Arrows Shift On Manager Review Form

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#64]
When going through items under Manager Review, the left and right arrows shift.  Screenshots won't help with this one.  Please go into Manager Review form.  As you go to the next record on the list, the arrows shift on the form between BC/TI/Issue and Strategic Task.

**Comment by milleniumchilld** [comment]
Morning, 

I will take a look at it and do a Mock up.

**Comment by Pawel062** [comment]
combined into 1 issue.
