### ISSUE TITLE
Add new "System" in Issues Database 

### ISSUE THREAD

**Issue by tcoma-ups** [CIMDBORG/CIMMigrationProject#65]
Opening this issue to document an update we want to make as far as adding a new 'system' in the issues database. For project planning purposes, we want to add the "AUTO" system to be able to manage a priority list of current things we are all working on. We have the functionality built already for our other applications and applying to our automation work would help maintain statuses and keep things in priority. Note that this system should NOT be visible in the meetings with supervisors/mangers. We can discuss more in our next team meeting.

**Comment by mikey2695** [comment]
This has been completed and added in version 3.0.0.2

**Comment by NickD0w** [comment]
Verified in production.
