### ISSUE TITLE
Issue with active status is missing from weekly review with applications

### ISSUE THREAD

**Issue by chrisdecicco** [CIMDBORG/CIMMigrationProject#67]
Issue 1384168 currently shows when I try to access the IB priority list going to browse items                  ->prioritize by system, but does not show up when trying to access through the weekly review with applications option.

**Comment by qdd8jtl** [comment]
@chrisdecicco  - haven't been able to look into this just yet, but your issue will sit unless you assign them out.  We all get an email notify if you assign to us and add the right labels on the right.

**Comment by Pawel062** [comment]
we were not able to recreate the issue and it has not shown up again for any new items.
