### ISSUE TITLE
Strategic Task Entry issue in Issues Database

### ISSUE THREAD

**Issue by mikey2695** [CIMDBORG/CIMMigrationProject#7]
Strategic Task is not able to be marked as a process improvement. 
Mike Fig will work on this.

**Comment by mikey2695** [comment]
This has now been fixed.

**Comment by NickD0w** [comment]
Looking to verify, I went to Add Task from Strategic Tasks menu,
See this...
![image](https://user-images.githubusercontent.com/59174086/72365223-cdf40500-36c5-11ea-8ce1-ea885ccc9cee.png)

 Use the Drop Down to select Strategic Task, the form changes, and get this...
![image](https://user-images.githubusercontent.com/59174086/72364948-5920cb00-36c5-11ea-90ba-96f6704b96ee.png)

Not seeing the Process Improvement box

**Comment by mikey2695** [comment]
Seems to be working on my end Nick. Make sure you're on version 2.0.0.2 (you'll see the version number on the login screen).

**Comment by NickD0w** [comment]
Yep, that was it, needed a recycle... Looks Good To Go! Thanks Mike!
![image](https://user-images.githubusercontent.com/59174086/72367265-ecf49600-36c9-11ea-9a26-24220b621b57.png)
