### ISSUE TITLE
Report : Export to Excel not Working

### ISSUE THREAD

**Issue by carrubba24** [CIMDBORG/CIMMigrationProject#72]
Not sure if this is something we are aware of currently, but when in the 'Report' screen & clicking 'Export to Excel' I receive this error message & failure to export. 

![image](https://user-images.githubusercontent.com/59064371/76761642-2ac37880-6766-11ea-8515-aa105176bb2b.png)

**Comment by brcox90** [comment]
Getting the same error as well.

**Comment by carrubba24** [comment]
Also noticing the error in trying to export from the 'Browse Items' screen. Is there a chance we consolidated the export function & made an error somewhere?

**Comment by mikey2695** [comment]
So this is what was happening...
When changes were last deployed, there was a mismatch in the minor versions in the Assembly Version and the Publish Version.

![image](https://user-images.githubusercontent.com/52287707/76976073-d0631d00-6909-11ea-8597-1f205800c770.png)

 
![image](https://user-images.githubusercontent.com/52287707/76976126-ebce2800-6909-11ea-9c5f-9168a117079f.png)

The minor versions (the circled value) MUST match. Goof on my part, sorry everyone.

**Comment by NickD0w** [comment]
It's always the little things that make the difference. Glad you found it. 
Verified working in production.
