### ISSUE TITLE
Unable to Close Resolved Issue for IB

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#75]
For IB Issue 937182, we are unable to close the issue.  Marked this as a higher impacting item since it will continue to remain on our Priority List.  Work-around will be to put it at the bottom of the list for now.

The following message appears when clicking Update:
Message - Update failed:  Must make changes to Title,Supplementary Details, Or Business Impacts.

**Comment by brcox90** [comment]
This seems to fixed. Close out 3 issues this morning including the one listed above without an error message.

**Comment by mikey2695** [comment]
Jan-Marie,
Can you close this with the newest update?
