### ISSUE TITLE
Add a User Friendly Message When Character Limit is Exceeded on a Form

### ISSUE THREAD

**Issue by kaylori77** [CIMDBORG/CIMMigrationProject#78]
Closing this issue since it's a duplicate of Issue #66 

When a user exceeds the number of characters allowed in a field, display a message stating the error. For Example: Maximum allowed characters for field exceeded.

Currently, user receives the following error: **Priority Number, BC/TI, One-Time Benefit and Annual Benefit must all be integer values** 

User clicks OK, then a system error displays.  User will not know what the exact error is & the first warning received is misleading.

This was found in the Edit/View Record form.  Same behavior would need to be visited on the other forms i.e. Add New Record form.

Screen shots below:

![image](https://user-images.githubusercontent.com/60524314/77783007-89260c00-702e-11ea-8a6e-0c495602ae4b.png)

![image](https://user-images.githubusercontent.com/60524314/77783041-92af7400-702e-11ea-8921-dd1fcd9f7537.png)

**Comment by brcox90** [comment]
@mikey2695 @tcoma-ups @Pawel062 @mortii09 

Let's include this on the code clean-up and try getting this done today so we can have it in there for the Monday update.

**Comment by qdd8jtl** [comment]
All - this is a duplicate of #66 opened earlier this month.  Can we close this one out and @kaylori77 add your comments/screenshots to the existing issue.

**Comment by kaylori77** [comment]
Closing this issue since it's a duplicate of Issue #66
