### ISSUE TITLE
Strategic Tasks Appear on the Manager Weekly Review 

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#8]
During the Manager Weekly Review, Strategic Tasks were appearing on the list.  These are supposed to be excluded from the list, similar to BC's as they are approved and reviewed separately.

[Issues-StrategicTask-Weekly.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4066971/Issues-StrategicTask-Weekly.docx)

**Comment by mikey2695** [comment]
Team,

This has been fixed. I have not published the changes, however; this will be done on Monday as discussed in yesterday's meeting.

**Comment by mikey2695** [comment]
Change has been made, go to go for weekly meeting tomorrow (1/22)
