### ISSUE TITLE
Error when updating/submitting edits to a record

### ISSUE THREAD

**Issue by brcox90** [CIMDBORG/CIMMigrationProject#84]
Happens when clicking "Update", Next Button, and Exit Button

<img width="881" alt="Capture" src="https://user-images.githubusercontent.com/59062755/78585802-75d22800-7808-11ea-8f4e-e461bdbc312d.PNG">

<img width="892" alt="Capture1" src="https://user-images.githubusercontent.com/59062755/78585809-77035500-7808-11ea-9209-2287d086bc76.PNG">

**Comment by Pawel062** [comment]
As per Brandon, unable to replicate so closing.
