### ISSUE TITLE
BID not appearing in the Open Items list

### ISSUE THREAD

**Issue by ellenculp** [CIMDBORG/CIMMigrationProject#85]

**Comment by Pawel062** [comment]
When you browse through open items, the BID ID field is empty. In the old database (and the way it should work in the new application) it would show in BID ID the BC/TI#. 
<img width="881" alt="Capture" src="https://user-images.githubusercontent.com/59065602/78802475-db9aed00-798b-11ea-9e96-dee6e6dd8bca.PNG">
