### ISSUE TITLE
Owner is not populated for a Strategic Task Entered In by User

### ISSUE THREAD

**Issue by qdd8jtl** [CIMDBORG/CIMMigrationProject#9]
BC/TI # 9459, System - EDI, Title - 'Include Mail Innovations in EDI PLD'

This item does not have an Owner populated and it is a mandatory field.  It does not look like the Owner field for Strategic Tasks functions the same as Issues/Defects/BC's where it is hard-coded based on the user.

- On Applications Weekly review Edit form, the owner is hard-coded

- On other forms, this is free-text and editable. 

- This Owner field also impacts reporting on numbers for My Talent End of Year reporting.
[Issues-MissingOwner.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4067210/Issues-MissingOwner.docx)

**Comment by mikey2695** [comment]
The reason the Owner field on a strategic task is not hard-coded is because a strategic task can have more than one person assigned to it. 

We should come to an agreement as to what the convention should be in regards to the Owner field all across the board.

**Comment by qdd8jtl** [comment]
I think Owner should be hard-coded by last name for consistency sake across the forms.  For Strategic Tasks, maybe we can have a team members field for those tasks that have more than one team member (or utilize the Supporting Details/Internal Notes to list).  

- For My Talent, end of year reporting it threw off the numbers because we couldn't determine who originally entered in the item for the goals so we had to adjust accordingly.

**Comment by mikey2695** [comment]
Understood. I think the team members field is the way to go, especially now that a lot of Strat Tasks are collaborative efforts rather than individual.

This change will go into effect, along with the updated version of the Weekly Review, on Monday.

**Comment by mikey2695** [comment]
Appears to have been fixed. Will have team test this before putting out changes on Monday

**Comment by mikey2695** [comment]
Enhancement has been implemented

**Comment by qdd8jtl** [comment]
During the weekly review, there was one item which did not have the Owner field populated.
BC/TI# 1446153, System  FCB
[Issues-MissingOwner2.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4097981/Issues-MissingOwner2.docx)

**Comment by mikey2695** [comment]
This was opened on 1/15, and the changes went into effect on 1/20, which explains why this did not have the owner field filled.
