### ISSUE TITLE
400 level items not included in Aging 

### ISSUE THREAD

**Issue by Pawel062** [CIMDBORG/CIMMigrationProject#90]
Items that are assigned a 400 level priority are not being including in the aging report or aging notifications.

**Comment by mikey2695** [comment]
Can I please get an example of this. A BC number will do.

**Comment by Pawel062** [comment]
438191:

![400_error](https://user-images.githubusercontent.com/59065602/81600714-0c5db000-9398-11ea-9fa8-561b04eab109.png)

**Comment by mikey2695** [comment]
This is the WHERE clause of the current query:

WHERE((Category LIKE 'BC%' AND(DATEDIFF(day, h1.Latest_Status_Update, CONVERT(date, GETDATE())) > 180))  
OR((Category NOT LIKE 'BC%' AND Impact NOT LIKE '%Not Billed Items%') AND(DATEDIFF(day, h1.Latest_Status_Update, CONVERT(date, GETDATE())) > 22))OR(Impact LIKE '%Not Billed Items%' 
AND(DATEDIFF(day, h1.Latest_Status_Update, CONVERT(date, GETDATE())) > 8))  
OR ((Category LIKE '%Strategic Task%' AND(DATEDIFF(day, h1.Latest_Status_Update, CONVERT(date, GETDATE())) > 14)))) AND(New_Issues.[Status] NOT LIKE '%closed%' 
AND New_Issues.[Status] NOT LIKE '%implemented%' AND New_Issues.[Status] NOT LIKE '%dropped%'
AND New_Issues.[Status] NOT LIKE '%deferred%' AND New_Issues.[Status] NOT LIKE '%Not Assigned%' AND New_Issues.[Status] NOT LIKE '%Completed%') ORDER BY TaskNum ASC; 

BC 1476109 would fall under Category NOT LIKE 'BC%' AND Impact NOT LIKE '%Not Billed Items%' - which would mean that it would age after 22 days without an update. We can make defects age quicker using a new criteria if needed.

**Comment by Pawel062** [comment]
Checked query and the aging is working correctly.
