### ISSUE TITLE
Users can close out issues without manager review being flagged

### ISSUE THREAD

**Issue by chrisdecicco** [CIMDBORG/CIMMigrationProject#93]
Issue 1643928 was flagged for updates required. Updates were made, but never marked as manager review. User was still able to close out issue in the database.

![image](https://user-images.githubusercontent.com/60188536/82601273-50616980-9b7d-11ea-964a-f5f95622965f.png)

**Comment by mikey2695** [comment]
Have to add the logic for this. We will address this tomorrow.

**Comment by Pawel062** [comment]
Changes implemented
