### ISSUE TITLE
Priority Numbers pasted from one record to another

### ISSUE THREAD

**Issue by Pawel062** [CIMDBORG/CIMMigrationProject#97]
In the issues database, when you go into edit/view records, then the priority number will be copied from one issue to another. So if you arrow through 4 items all 4 will use the priority number of the first item you opened. This is causing multiple items to have 101, 201, etc.

The work around is to use the weekly review forms to go through your items.

**Comment by mikey2695** [comment]
This fix has been tested and implemented.
